---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5d8cc0abe95056001408bed4/webhook/forestry'
sections:
  - type: directory
    path: content/posts
    match: '**/*'
    label: Post
    create: all
    templates:
      - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
